# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Medidex' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Medidex
  pod 'Alamofire', '~> 4.4'
  pod 'KeychainAccess', '~> 3.0.2’
  pod 'SCLAlertView'
  pod 'SideMenu'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'JSQMessagesViewController'
  pod 'ScrollableGraphView'
  pod 'ASHorizontalScrollView', '~> 1.5.1'∫

  target 'MedidexTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MedidexUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
